- name: Disable Default Nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enabling Nodejs:18
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Configure Backend
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Adding User
  ansible.builtin.user:
    name: expense

- name: App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_requi.yml

- name: Downloading/Install Dependencies
  community.general.npm:
    path: /app

- name: Reloading and Restarting Backend
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Install MYSQL & Python Library for MYSQL
  ansible.builtin.dnf:
    name: "{{item}}"
    state: installed
  loop:
    - mysql
    - python3-PyMySQL

- name: Loading Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.expense.rds.username', region='us-east-1' ) }}"
    login_password: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.expense.rds.password', region='us-east-1' ) }}"
    login_host: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.expense.rds.endpoint', region='us-east-1' ) }}"