- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copying Application Contents
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_requi.yml

- name: Enabling and Starting Nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted